### ISSUE TITLE
yes, another memory leaking

### ISSUE THREAD

**Issue by OneFingerCodingWarrior** [mono/monotorrent#102]
![image](https://user-images.githubusercontent.com/53161726/62292450-05b11c80-b499-11e9-9a97-80d4ed2437a6.png)
![image](https://user-images.githubusercontent.com/53161726/62292600-5759a700-b499-11e9-9378-db19b78fcdbd.png)
I will update soon

**Comment by OneFingerCodingWarrior** [comment]
maybe it's not a bug, I will update after confirm

**Comment by OneFingerCodingWarrior** [comment]
there are 40,000 HaveMessager reference by PeerId, I wait the torrent manager download complete, and delete the torrent task, the memory still didn't get released.

I add my fix sendQueue.clear(); to the PeerId.Dispose(); //with no effect, memory occupation still up to 70MB

I will try to figured out what happend

**Comment by OneFingerCodingWarrior** [comment]
Hi, Alan, I have a question, All the HaveMessage is packed into one MessageBundle, is it OK to send MessageBundle directly to the peer ?

**Comment by alanmcgovern** [comment]
Hrmm... When `CleanupConnection` is run, the `PeerId` object is supposed to be removed from every list/dictionary/etc and should be eligible for garbage collection. Are you seeing lots of `HaveMessages` *and* also a few dozen/hundred `PeerId` objects being retained accidentally?

`MessageBundle` is just a convenience to make it easier to send multiple messages in one go. I think it's mostly used for `HaveMessage`s and `RequestMessage`s.  When we encode a `MessageBundle` to a `byte[]` it's basically the same as encoding (and sending) each message one by one. The only actual difference is that instead of making 10 calls to `socket.Send` to send 10 messages of length 20bytes, we make one `socket.Send` call to send 200 bytes because we write all 10 messages to the buffer.

**Comment by OneFingerCodingWarrior** [comment]
ok, I got it

**Comment by alanmcgovern** [comment]
Just to update this. These are the results from the profiler after downloading a 700MB ubuntu torrent:

1. Total object allocations (215 MB)
<img width="1237" alt="Screenshot 2019-08-02 at 16 22 44" src="https://user-images.githubusercontent.com/264396/62380797-e3270e00-b541-11e9-8c58-ef67190732f3.png">

2. Objects alive a few seconds after downloading completes (2.43 MB)
<img width="1232" alt="Screenshot 2019-08-02 at 16 23 05" src="https://user-images.githubusercontent.com/264396/62380816-f0dc9380-b541-11e9-97a4-da1712bf760d.png">

3. Pretty graph of the largest objects
<img width="1228" alt="Screenshot 2019-08-02 at 16 25 31" src="https://user-images.githubusercontent.com/264396/62380908-2da88a80-b542-11e9-8b10-606b5b7b9bd5.png">

**Comment by OneFingerCodingWarrior** [comment]
it is impossible for me to fix this bug,

**Comment by alanmcgovern** [comment]
If you see any other issues do let me know! :) Patches are welcome too, when you can :)

**Comment by OneFingerCodingWarrior** [comment]
now the engine will not stuck, and memory leaking is fixed, I think there will be no big issue. if I find something, there is no doubt I will definitely back to your advice^_^
