### ISSUE TITLE
memory leaking ? with no idea how to fix

### ISSUE THREAD

**Issue by OneFingerCodingWarrior** [mono/monotorrent#105]
I download the test torrent, the memory occupation raised to 30MB, I delete the task, nothing changed, and the memory looks just fine, 
![image](https://user-images.githubusercontent.com/53161726/62407932-f6de7d00-b5f2-11e9-9fcd-6c28f46e7174.png)

I wait for a while, the memory dropped to 25MB

![image](https://user-images.githubusercontent.com/53161726/62407951-32794700-b5f3-11e9-8fe0-592517737718.png)
![image](https://user-images.githubusercontent.com/53161726/62407959-50df4280-b5f3-11e9-985f-7a7c1ee2c49f.png)
is this a real leaking ?

**Comment by OneFingerCodingWarrior** [comment]
test torrent file's InfoHash = {43-EA-FD-98-95-F0-49-F2-F5-B9-21-19-92-C0-8B-EA-17-9F-C6-E5}
name Avengers Endgame 2019 720p WEBRip X264-ORCA88

**Comment by alanmcgovern** [comment]
It's hard to tell what's going on from that, but I'd say it's unlikely to be a real leak.

When you download your first torrent, a few static caches are created. The memory for these is never released. One example is `ClientEngine.BufferManager` - the `byte[]` in this cache are never freed as they will always be needed. Also, you have DHT enabled. It's normal for the DHT engine to consume a few MB of memory (i haven't measured it exactly), as it stores information for hundreds or thousands of peers/nodes. I have not extensively profiled DHT, but it doesn't look like it's causing a problem :)

I generally do my profiling with DHT disabled just because it makes it a little easier to see exactly what's going on when torrents are downloading. Similarly, if i wanted to see the performance of the DHT  code I would profile it without downloading a torrent. 

Finally, I agree that these static caches could be cleared when all torrents have been stopped, but that level of optimisation isn't too important. The DHT engine will continue to use memory until it is stopped, as an active/running DHT node is useful even when no torrents are actively downloading.

**Comment by alanmcgovern** [comment]
If you do have issues, do let me know what I should look at!

**Comment by OneFingerCodingWarrior** [comment]
you are right,  alan , it's perfectly normal for the memory occupation used by some necessary data and struct. thanks
