### ISSUE TITLE
Pause didn't pauses Hashing.

### ISSUE THREAD

**Issue by justscribe** [mono/monotorrent#138]
Hi,

So the issue is calling PauseAsync didn't pause Hashing mode of TorrentManager.

**Comment by alanmcgovern** [comment]
Let me know if the changes in that pull request work as expected! This was a missing feature :)

**Comment by justscribe** [comment]
Hi,

I've checked the solution and It didn't work as should.
After the call of **PauseAsync**, the're no event from **TorrentStateChanged** and the **TorrentManager.State** didn't changed to **Paused** or **HashingPaused**.

**Comment by alanmcgovern** [comment]
I think the pausing/resuming did work as expected, but the state wasn't being updated because the event wasn't being emitted. Also I had to remove the `Paused` boolean from the class as it wasn't actually being used :P

The latest iteration has tests to ensure the state changes, and it appears to pause/resume as expected.

http://recordit.co/Q2SNnpks2I

I added this change locally to verify manually: https://gist.github.com/alanmcgovern/77d90c55456c62c356d884b8273d07cb

**Comment by alanmcgovern** [comment]
Should be implemented now!
