### ISSUE TITLE
TorrentStateChanged event throws an exception when calling StopAsync.

### ISSUE THREAD

**Issue by justscribe** [mono/monotorrent#143]
Hi,

Even if all the code inside **TorrentStateChanged** handler inside try/catch block, I still receiving the **OperationCanceledException**, and can't handle it. As the solution I just removing handler from subscribers before Stop, but that is a weird solution)
I think better do not throw the exception, just change the State is enought.
Thank you.

**Comment by alanmcgovern** [comment]
Do you have a stacktrace showing the issue? It'd help me figure out what's going wrong. Thanks!

**Comment by justscribe** [comment]
25.09.2019 15:54:52> The operation was canceled. | System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.CancellationToken.ThrowIfCancellationRequested()
   at MonoTorrent.Client.Modes.HashingMode.<WaitForHashingToComplete>d__9.MoveNext() | _torrentManager_TorrentStateChanged

**Comment by justscribe** [comment]
I can't reproduce that in "do-not-download" branch, seems it was in "pause-hashing".

**Comment by alanmcgovern** [comment]
Oh interesting, i wonder if i'm missing a try/catch in that new code :) I'll check it out some more to make sure cancellation is handled correctly in that branch!

**Comment by alanmcgovern** [comment]
I can't reproduce that issue in the current `pause-hashing` branch and I did add two further tests to ensure things are working as expected. They were :)

`HashingMode` is instantiated in one place. https://github.com/mono/monotorrent/blob/6a1081e23a42a5c1539bcd520d4a829cab6c1b61/src/MonoTorrent/MonoTorrent.Client/Managers/TorrentManager.cs#L459-L475 . If the hash is cancelled then a TaskCanceledException/OperationCanceledException will be thrown by the `WaitForHashingToComplete` method (due to the use of the TaskCancellationSource) and we'll hit the `catch` statement and do nothing.

If you're seeing an *unhandled* exception somewhere, then let me know how you're triggering it, and if there is any further information to explain the stacktrace that would help me.

Thanks!

**Comment by justscribe** [comment]
Can't reproduce.
