### ISSUE TITLE
Second call of StartAsync after StopAsync poorly finds peers/seeds

### ISSUE THREAD

**Issue by catholic** [mono/monotorrent#156]
When I first time call StartAsync of certain TorrentManager, peers/seeds are found very quickly.

But if I call TorrentManager's StopAsync and after that StartAsync, peers/seeds are missed and new ones not found at all or found a few. And it takes much more time to find them, 30 seconds or more.

If I call StartAsync on another TorrentManager, peers/seeds are found very quickly as well. But only for the first time.

Any ideas why this happening?

**Comment by alanmcgovern** [comment]
Are you relying on `Dht` or a `Tracker` to retrieve peers?

1) If it's a tracker, can you attach to `ClientEngine.TrackerManager.AnnounceComplete` and log the success/failure of the tracker invocation? You can also log the list of peers which the tracker returned by accessing `AnnounceResponseEventArgs.Peers`. If the list is more or less the same for both invocations, and it's successful both times, then the issues is probably something quite unusual.

2) If it's Dht then can you attach to `DhtEngine.PeersFound` and make sure that it is being raised the second time you start the torrent, and that enough valid peers are being found.

**Comment by catholic** [comment]
As I suppose, both are used, Dht and Tracker if it's set.
I will try things you suggested on Monday and will post my results here.
Thanks for the help!

**Comment by alanmcgovern** [comment]
When you do try it, can you use the latest commit from master? I think it could make a difference :) I'll be issuing a release of it soon!

**Comment by alanmcgovern** [comment]
Try 1.0.6 or newer, and if the problem persists let me know the answers to the question I asked previously :)

Thanks!

**Comment by catholic** [comment]
> 1. If the list is more or less the same for both invocations, and it's successful both times, then the issues is probably something quite unusual.

After StopAsync() -> StartAsync() on AnnounceComplete, the length of Peers list is the same as it was for the first StartAsync() call

> 2. DhtEngine.PeersFound

DhtEngine.PeersFound event is raising fast multiple times after the first call of StartAsync() and the download starts fast.

After StopAsync() -> StartAsync() PeersFound event not raising for a long time and download is not starting, even TorrentManager shows that at has Peers. It shows Seeds as 0. I suppose it because Peers found from Tracker are not compatible at the moment for the needs to download needed pieces. So we need more peers from DhtEngine.

If I wait for 2-3 minutes after StopAsync() and then call StartAsync(), a download starts the same fast as StartAsync() was called for the first time. 

So, it seems that DhtEngine needs some force to start peers search again after second StartAsync()

**Comment by alanmcgovern** [comment]
I can look into this later. It sounds like the announce is either being incorrectly skipped, or perhaps the tracker is deliberately not returning peers due to multiple announce requests arriving too quickly.

It would also help restart performance if the list of peers was not cleared when stopping and starting a torrent. The memory retention would be relatively tiny in this scenario.

**Comment by alanmcgovern** [comment]
I just did a quick screencast of a StopAsync/StartAsync loop with a 30 second delay between changes.

https://recordit.co/CMKHdP5pwq

An initial start seems to take a few seconds to create 50+ connections, but after a stop and a start it seems to take a bit longer alright. I don't know if it's different enough to be a problem as I still end up with about 1 connection per second. I'll dig into a little more, but I wanted to first check two things:

1) Which version of the library are you using (or which commit if you're compiling from source)?
2) Does my screencast match what you're seeing?

**Comment by alanmcgovern** [comment]
On Windows the performance is significantly better. It takes a few seconds to reach 70+ connections on my computer after a StopAsync, a delay of 30 seconds, and a StartAsync.

**Comment by catholic** [comment]
1. I'm using the Master source with the latest commit, compiling library by myself.
2. On your screencast, I don't see any delay. If it presents, it's really fast enough to be not a problem at all.

I'm testing on android. Do you have any android device? I can send you the link for .apk of my app. It's still not yet released to Google Play.

**Comment by alanmcgovern** [comment]
Interesting! Android should have *reasonably* similar performance characteristics to the MacOS screenshot I recorded as Xamarin.Android is based on Mono. There may be platform specific performance or stability issues, but hopefully this isn't one of those cases.

I could load an APK into an emulator, or a device, to test but  it would be hard to diagnose anything if I cannot make changes to the underlying code. If you could record a screencast, or video, showing the performance that would give me a better idea of the difference you're seeing. I do think MacOS is showing a noticeable, but not too bad, drop in performance. This performance drop could be worse on Android (if it really is a thing and not just a glitch in testing :p ). 

Please keep an eye on things with the latest monotorrent build, and if you think there is still a performance drop when stopping and starting then fire off an email with your testcase to my email address ( https://github.com/mono/monotorrent/blob/master/src/MonoTorrent/MonoTorrent.BEncoding/BEncodedDictionary.cs#L5 ) and I'll review what I can.

**Comment by catholic** [comment]
Ok. Thanks. I'll do some more tests, on Android and on Windows also. I will post results later.

**Comment by alanmcgovern** [comment]
@catholic have you gotten a chance to test things out more thoroughly? If so, are you still seeing issues or are things working well now?

**Comment by catholic** [comment]
The issue still presents in my app. I have no idea how this can be fixed. 

On windows, the behavior is the same. The second call of StartAsync() takes a much longer time to start the download. Peers are found, but the download doesn't start immediately.

The issue ticket can be closed for now. I will create a new one if I have more to say.

**Comment by alanmcgovern** [comment]
It's ok to leave this open for now. I'll do some more reviewing and see if I can figure out what the difference is. I think I can replicate a similar kind of issue on MacOS so perhaps if I keep digging into it I'll be able to figure it out!

**Comment by catholic** [comment]
After a lot of testing, I have some observations.

It seems that the key problem is converting AvailablePeers to ConnectedPeers if TorrentManager has a lot of AvailablePeers from the beginning (the first iteration or something like that). I understand this sounds illogical.

But I have tested this on popular torrents, 1000 peers and more.
The more peers found at the beginning the fewer chances they will be converted to ConnectedPeers.

On extremely popular torrents, 10000 peers and more, the first ConnectedPeers appear after minutes or even doesn't appear a lot.

And if this is the problem, it seems logical that the second start (when some AvailablePeers already present) takes much longer time to convert them to ConnectedPeers, which causes download not starting.

**Comment by alanmcgovern** [comment]
I made some changes to SampleClient to help diagnose the issue. https://github.com/mono/monotorrent/tree/issue-156 . Specifically every 25 seconds i stop the torrent, wait 15 seconds, then start it again: https://github.com/mono/monotorrent/commit/3e500635c5a178735f0bdbf62fe40b0bed012e84#diff-b0436d8ebd7b26c810e684eda1472823R196-R201.

I added one new event for when a connection attempt is initiated, and then ensured i logged the success and failure cases too. The screencast didn't upload, but you can examine the logging here and see how quickly things are re-connecting for me: https://gist.github.com/alanmcgovern/d2351ba2ff2209f493712073f1cd8f64 . It's super fast on MacOS.

If you can log the same connection related events, with the same timestamp I might be able to figure out which aspect is problematic. This is an odd problem!

**Comment by alanmcgovern** [comment]
I just removed this [check](https://github.com/mono/monotorrent/commit/cc522bfe31308ecaf018e52f36bad25a27abbeec). At the time i was debugger connection creation and needed things to not time out while I was validating things. I shouldn't have committed this change as it could make connections really slow to establish when the debugger is attached.

**Comment by catholic** [comment]
Thank you very much for help.
Please give me a day to make some tests with the information you gave me.

Mostly I'm getting these reasons of connections fail:

Connection failed!!!: ipv4://**.***.***.***:30158/ - Unreachable - All
Connection failed!!!: ipv4://***.***.***.***:48078/ - HandshakeFailed - RC4Header, RC4Full
Connection failed!!!: ipv4://**.**.***.***:45508/ - EncryptionNegiotiationFailed - None

Will post more information later

**Comment by alanmcgovern** [comment]
Can you print timestamps along with every connectoin started/failed/succeeded event? The interesting part for me is whether or not the number of connections per second changes in a noticeable way, or if the success/failure ratio changes over time. Timestamps will be very useful in understanding this.

If a peer is `Unreachable` then it is immediately discarded and won't be tried again. Unreachable peers are usually offline or do not have proper port forwarding. We can probably ignore these as they're relatively normal.

`HandshakeFailed - RC4Header, RC4Full` implies that 'EngineSettings.PreferEncryption' is set to false. It might be worth setting this to true and seeing if that affects the success ratio. If plain text connections are used by default then it's more likely that the first iteration will fail due to ISPs closing connections which start with a bittorrent handshake.

One thing that can be interesting is to look at the IP/port and see if there's an obvious pattern of "the first unencrypted connection fails, then the second encrypted one succeeds". That can indicate an ISP is interfering with the connections.

**Comment by catholic** [comment]
It seems that EngineSettings.PreferEncryption did the trick. The problem solved.

For popular torrents a lot of peers are Unreachable and it takes time to pass them by. But in the end a couple of dozens of good peers are found. On second StartAsync the behavior is pretty the same.

Thanks for the help!

Here are couple of my logs (IPs are hidden)
https://pastebin.com/raw/wzr1pcC6
https://pastebin.com/raw/fFy1HTuQ
https://pastebin.com/raw/BCKrdGDS

**Comment by alanmcgovern** [comment]
That is an incredibly high number of unreachable peers. The only place the `Unreachable` status is used is here: https://github.com/mono/monotorrent/blob/cc522bfe31308ecaf018e52f36bad25a27abbeec/src/MonoTorrent/MonoTorrent.Client/Managers/ConnectionManager.cs#L131-L151 . Which means `SocketConnection.ConnectAsync` is failing to connect. That seems pretty unlikely to be causing an issue though, so I would stand by my guess of peers being offline, or being unreachable due to NAT issues.

There are a few things you can try to help speed up the connection rate.

1) Reduce the connection timeout. This is not exposed to the user, but i'll add that to EngineSettings in a few minutes. The default is 10 seconds, but you could try dropping it to 7 seconds (or lower?) at the risk of losing out on some viable connections. 

2) Increase `EngineSettings. MaximumHalfOpenConnections`. The default is 8, but if you increase this then the engine will have more concurrent connection attempts. Windows XP used to cause connection attempts to fail immediately if you had more than 10 concurrent connection attempts. I believe that limit has been removed again with windows 7 and newer. If this is correct then increasing this to 15 or 20 might be the best way around the problem. Do note that some consumer grade routers will have issues if you raise this number too high. I would highly recommend keeping this number under 20.

Similarly, if you have raised this number above the default, you should try it at it's default value of 8 and see if it results in better or worse behaviour :)

**Comment by alanmcgovern** [comment]
Also, i am glad to hear that preferring encryption solved the issue! I toggled the default to 'true' a few months back due to someone else seeing the same issue :)

**Comment by catholic** [comment]
Right now MaximumHalfOpenConnections is set as 20. I will test this moment next week.

**Comment by sdluxeon** [comment]
Hey guys, I was having the same issue but nothing from the above helped. However I noticed that even after calling StopAsync() there were some peers left and the downloading was continuing slowly. Tracked down the problem to here:
https://github.com/mono/monotorrent/blob/ad279e59da9c5dc271a65d9f4958bc9eab2aafbc/src/MonoTorrent/MonoTorrent.Client/Modes/StoppingMode.cs#L53-L60
Moving `Manager.Peers.ClearAll()` after the "CleanupSocket" fixed it for me. Cheers!
