### ISSUE TITLE
Reusabletasks error

### ISSUE THREAD

**Issue by OneFingerCodingWarrior** [mono/monotorrent#182]
![image](https://user-images.githubusercontent.com/53161726/68985016-7a447700-084e-11ea-8c0b-484d3228356d.png)
after downloading for minutes exception throwed

**Comment by OneFingerCodingWarrior** [comment]
![image](https://user-images.githubusercontent.com/53161726/68991160-b0a5e480-0896-11ea-85a4-b914c0108f51.png)

**Comment by alanmcgovern** [comment]
I'm going to fix https://github.com/mono/monotorrent/issues/181 as I think the two issues are probably related. That one has a bit more information in it which may help me solve the problem!

**Comment by alanmcgovern** [comment]
I think this issue could be fixed by https://github.com/alanmcgovern/ReusableTasks/commit/46e2183db35fb36154a0d4c9be986e00187a9928 as the stacktrace does show NetworkIO.SendAsync. If you can still reproduce the issue with ReusableTasks 1.0.5 then please reopen this and I'll investigate some more!

Thanks!
