### ISSUE TITLE
How to download pieces sequential from start to end?

### ISSUE THREAD

**Issue by uponatime2019** [mono/monotorrent#203]
How can I implement download sequential for media files. I looked at MonoTorrent.Client.PiecePicking but no class implement this feature. Thanks

**Comment by f5inet** [comment]
You must rewrite your own piecepicker. you can start refactoring the new one from RandomisedPicker.cs, and name it 'StreamingPicker.cs'
Also, you may want to 'fast pick' the start and the end pieces of the files first, because if you want to view as you download the multimedia file, usually the player needs to read the lasts bytes.

**Comment by uponatime2019** [comment]
@f5inet can you explain what count, startIndex and endIndex meanings
`        public virtual IList<PieceRequest> PickPiece(IPieceRequester peer, BitField available, IReadOnlyList<IPieceRequester> otherPeers, int count, int startIndex, int endIndex)`

**Comment by alanmcgovern** [comment]
There's a SlidingWindow picker which implements this behaviour. 

There's no pure sequential picker as that's very much against how BitTorrent is supposed to work. The SlidingWindow picker is a hybrid which uses sequential for the next 10-15 pieces you need, but uses normal randomised picking for everything else once those have been downloaded.

**Comment by ilyalatt** [comment]
@uponatime2019
You can check out https://github.com/ilyalatt/BitTorrentStorage. It implements [custom piece picker](https://github.com/ilyalatt/BitTorrentStorage/blob/master/src/BitTorrentStorage/CustomPiecePicker.cs). It is not efficient at all but should give you an idea.

**Comment by ilyalatt** [comment]
@alanmcgovern 
I guess it is not against of how BitTorrent is supposed to work if there are a lot of seeders, especially for private trackers that tracks ratio.

**Comment by alanmcgovern** [comment]
> @alanmcgovern
> I guess it is not against of how BitTorrent is supposed to work if there are a lot of seeders. Especially for private trackers that track ratio. Such trackers have a lot of competing seeders that tear each other to give leechers as mush as possible as quick as possible to enhance ratio.

Yes and no. Speed of sharing is not directly linked to rarest-first piece picking.

Rarest first is used to ensure torrents survive longer and shouldn't negatively affect the speed at which someone downloads. Sliding window picking is an optimisation to ensure the next X megabytes are downloaded at highest priority, and everything after that is normal rarest-first. You can adjust the set which is considered highest priority. 

Sequential picking causes poorer torrent longevity and has no benefits over sliding window picking. 

Let me update the documentation on this anyway as it's trivial to have a 99% sequential piece picker if that's what you truly need. SlidingWindow is also built in and is more than likely exactly what you need.

**Comment by alanmcgovern** [comment]
@f5inet @ilyalatt I'm contemplating integrating a basic HTTP streamer into monotorrent. The idea is that if you're trying to implement streaming audio or streaming video, and your media player can play from a HTTP source, or any old seekable Stream, then I can make your integration *much much* simpler by exposing a special `Stream` implemementation, or 'http server', which you can give to your media player.

This means I could take care of all the piece prioritisation/downloading inside MonoTorrent itself so no-one has to deal with SlidingWindowPicker or things like that.

This is an example of how VLC could be made stream a torrent. This sample implementation reads the data from a file on-disk, but it would be possible to integrate it with `TorrentManager` and `SlidingWindowPicker` so that everything Just Works (tm).

If this is something that would be useful/interesting for your usecases, please drop some comments on this issue:  https://github.com/mono/monotorrent/issues/205#issuecomment-575238761

If it's not useful, but you have ideas on better approaches/features, do add that information!
